collections:
  - name: redhat.satellite
    source: https://cloud.redhat.com/api/automation-hub/

  - name: community.general
    source: https://galaxy.ansible.com

  - name: ansible.posix
    source: https://galaxy.ansible.com
