---
- name: Automation | Ansible | Satellite | Install Satellite Packages
  ansible.builtin.yum:
    name: "{{ satellite_packages }}"
    state: present

- name: Automation | Ansible | Satellite | Start chronyd service
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ satellite_services }}"

- name: Automation | Ansible | Satellite | Firewalld Configuration
  ansible.posix.firewalld:
    immediate: true
    permanent: true
    service: "{{ item }}"
    state: enabled
  loop: "{{ satellite_firewall_rules }}"

- name: Automation | Ansible | Satellite | Place answerfile on filesystem
  ansible.builtin.template:
    src: satellite-answerfile.yaml.j2
    dest: /etc/foreman-installer/scenarios.d/satellite-answers.yaml
    owner:  root
    group: root

- name: Automation | Ansible | Satellite | Install Satellite Server
  ansible-builtin.shell: >
    satellite-installer --scenario satellite
  args:
    creates: /etc/httpd/conf.d/05-foreman-ssl.conf
  run_once: true
